service: poc-simple-lambda-dd-integration

provider:
  name: aws
  runtime: nodejs12.x
  tracing:
    lambda: true
    apiGateway: true

plugins:
  - serverless-plugin-datadog

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET hello

custom:
  datadog:
    # https://docs.datadoghq.com/infrastructure/serverless/datadog_lambda_layer/
    # Send custom metrics via logs with the help of Datadog Forwarder Lambda function (recommended). Defaults to false.
    flushMetricsToLogs: true

    # When set, the plugin will try to subscribe the lambda's cloudwatch log groups to the forwarder with the given arn.
    forwarder: XXXXXXXXXXXX

